### ISSUE TITLE
Won't compile, issue with stdint.h?

### ISSUE THREAD

**Issue by x3l51** [nsd20463/ps2_kbd_to_usb_adapter#1]
Hi Nicolas! First thanks for providing this opportunity to get older keyboards to work again! However I've ran into a fatal error while trying to compile everything. Probably you have an idea on how to solve this? Thanks in advance!

```
root@THINKPAD-E330:/home/xl3/keyboard/ps2_kbd_to_usb_adapter# make
 [INFO]    : Begin compilation of project "adapter"...

avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 [GCC]     : Compiling C file "main.c"
avr-gcc -c -pipe -gdwarf-2 -g2 -mmcu=atmega32u4 -fshort-enums -fno-inline-small-functions -fpack-struct -Wall -fno-strict-aliasing -funsigned-char -funsigned-bitfields
-ffunction-sections -I. -I/mnt/c/Users/Nicolas/Desktop/lufa-LUFA-140302/lufa-LUFA-140302/LUFA/.. -DARCH=ARCH_AVR8 -DBOARD=BOARD_ADAFRUITU4 -DF_USB=16000000UL -DF_CPU=16
000000UL -mrelax -x c -Os -std=gnu99 -Wstrict-prototypes -Wall -DUSE_LUFA_CONFIG_HEADER -fpack-struct -fshort-enums -funsigned-char -funsigned-bitfields  -MMD -MP -MF m
ain.d main.c -o main.o
In file included from /mnt/c/Users/Nicolas/Desktop/lufa-LUFA-140302/lufa-LUFA-140302/LUFA/../LUFA/Drivers/USB/../../Common/Common.h:66:0,
                 from /mnt/c/Users/Nicolas/Desktop/lufa-LUFA-140302/lufa-LUFA-140302/LUFA/../LUFA/Drivers/USB/USB.h:382,
                 from main.c:186:
/usr/lib/gcc/avr/4.9.2/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                          ^
compilation terminated.
/mnt/c/Users/Nicolas/Desktop/lufa-LUFA-140302/lufa-LUFA-140302/LUFA/Build/lufa_build.mk:286: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

**Comment by nsd20463** [comment]
Something isn't right in your gcc-avr installation. Normally the next file named "stdint.h" in the include path is /usr/lib/avr/include/stdint.h, and that's the one with the meat in it.

Attached is the output of me compiling after adding the "-H" flag to CC_FLAGS in Makefile so gcc dumps out the path of each file it #includes.

[output.txt](https://github.com/nsd20463/ps2_kbd_to_usb_adapter/files/1690468/output.txt)

**Comment by x3l51** [comment]
I have no `stdint.h` in `/usr/lib/avr/include/stdint.h`. I don't even have the folder `/include`.

´´´
xl4@xl4 /usr/lib/avr $ ls -alt
total 28
drwxr-xr-x   2 root root  4096 Feb  3 19:05 bin
drwxr-xr-x   5 root root  4096 Feb  3 19:05 .
drwxr-xr-x   3 root root  4096 Feb  3 19:05 lib
drwxr-xr-x   4 root root  4096 Feb  3 19:05 x86_64-linux-gnu
drwxr-xr-x 171 root root 12288 Feb  3 19:05 ..
´´´

Also I am now testing on another machine. My first try to compile was via the win10 linux subsystem and I figured that could have caused the problem. But not I am facing the same error.

I googled around and found [this](https://stackoverflow.com/a/19929441) and [that](https://github.com/linux-sunxi/sunxi-tools/issues/23) but nothing did the trick. I am running a an week old install of mint so I'm guessing it should be fine.

I just now looked for how avr instead of gcc and found that avr-libc is completely missing but necessary for compiling this.

`sudo aptitude install avr-libc` did the trick for me. `[INFO]    : Finished building project "adapter".`

Probably you could include this in your how-to? Thanks for you help!!
